# Generated by Django 4.2.10 on 2025-08-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_remove_strategicinitiative_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicinitiative',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Whether this initiative is a default one created by admin'),
        ),
    ]
