# Generated by Django 4.2.10 on 2025-08-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_strategicinitiative_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybudget',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_budgets', to='organizations.mainactivity'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='annual_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='q1_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q1 Target (Jul-Sep)'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='q2_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q2 Target (Oct-Dec)'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='q3_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q3 Target (Jan-Mar)'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='q4_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Q4 Target (Apr-Jun)'),
        ),
        migrations.CreateModel(
            name='SubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('Training', 'Training'), ('Meeting', 'Meeting'), ('Workshop', 'Workshop'), ('Printing', 'Printing'), ('Supervision', 'Supervision'), ('Procurement', 'Procurement'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='organizations.mainactivity')),
            ],
            options={
                'verbose_name': 'Sub Activity',
                'verbose_name_plural': 'Sub Activities',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='activitybudget',
            name='sub_activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='organizations.subactivity'),
        ),
    ]
