# Generated by Django 4.2.10 on 2025-08-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_alter_activitybudget_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactivity',
            name='budget_calculation_type',
            field=models.CharField(choices=[('WITH_TOOL', 'With Tool'), ('WITHOUT_TOOL', 'Without Tool')], default='WITHOUT_TOOL', max_length=20),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='estimated_cost_with_tool',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='estimated_cost_without_tool',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='government_treasury',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='meeting_workshop_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='other_funding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='partners_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='partners_funding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='printing_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='procurement_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='sdg_funding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='supervision_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='training_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
